# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='subtitle',
            field=models.CharField(default='Author forgot to put subtitle! LOL', max_length=500),
        ),
    ]
