# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20161005_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='link',
            field=models.CharField(default='sjKc6N', max_length=40),
        ),
    ]
