# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_topic_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=index.models.get_image_path)),
            ],
        ),
        migrations.AlterField(
            model_name='topic',
            name='link',
            field=models.CharField(default='aP6ZJF', max_length=40),
        ),
        migrations.AddField(
            model_name='images',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Topic'),
        ),
    ]
