# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-03 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20161011_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='link',
            field=models.CharField(default='wOieeB', max_length=40),
        ),
    ]
