# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-04 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20170204_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='link',
            field=models.CharField(default='tGPXJs', max_length=40),
        ),
    ]
